import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Script client pour enregistrer la page précédente
  const storeCurrentPageAsReferer = `
    (function() {
      if (typeof window !== 'undefined') {
        // Ne pas enregistrer les URL de Stripe ou les pages d'erreur
        if (!window.location.href.includes('stripe.com') &&
            !window.location.href.includes('/error') &&
            !window.location.href.includes('/subscription/cancel') &&
            !window.location.href.includes('/subscription/success')) {
          sessionStorage.setItem('previousPage', window.location.pathname);
        }
      }
    })();
  `;

  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Script pour suivre la navigation */}
        <script dangerouslySetInnerHTML={{ __html: storeCurrentPageAsReferer }} />
        {children}
      </body>
    </html>
  );
}
